language: node_js
node_js:
- stable
script:
- npm run pretest
- npm run test
- npm run generate
cache:
  directories:
  - node_modules
deploy:
  provider: gcs
  access_key_id: $GCS_ACCESS_KEY
  secret_access_key:
    secure: $GCS_SECRET_KEY
  bucket: $GCS_BUCKET
  local-dir: dist
  on:
    repo: fightforthefuture/earth-day-live
